corrected fasta

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -6,7 +6,7 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at https://mozilla.org/MPL/2.0/.
 
-#set -e
+set -e
 cd `dirname $0`
 
 ediff() {
@@ -31,6 +31,10 @@ for f in input/*.pdb;do
 	../bin/extract -c A $f | ediff output/${name}_A.pdb
 
 	../bin/fasta $f | ediff output/$name.fasta
+
+	if [[ `../bin/rmsd $f output/${name}_translate_x100.pdb` != "+1.001e+02" ]]; then
+		echo "rmsd error" 1>&2 
+	fi
 done
 
 f=input/3zev.pdb
